// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjvig4a9wl_TKUJJ7SocfR_pD9yLkL8vs',
    appId: '1:533485142059:web:8d3e53e7971b54ad252a6e',
    messagingSenderId: '533485142059',
    projectId: 'app-mais-saude-73627',
    authDomain: 'app-mais-saude-73627.firebaseapp.com',
    storageBucket: 'app-mais-saude-73627.appspot.com',
    measurementId: 'G-EC8K691QZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAjjDaGVf9uoRF8ki-gQL6A3pEyCS96s8',
    appId: '1:533485142059:android:e975e35a58c2f39d252a6e',
    messagingSenderId: '533485142059',
    projectId: 'app-mais-saude-73627',
    storageBucket: 'app-mais-saude-73627.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClhm0AUmtspEMqWgiGfvXmUiBHoH7EwJc',
    appId: '1:533485142059:ios:6c65799b1816956b252a6e',
    messagingSenderId: '533485142059',
    projectId: 'app-mais-saude-73627',
    storageBucket: 'app-mais-saude-73627.appspot.com',
    iosBundleId: 'com.example.appMaisSaude',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClhm0AUmtspEMqWgiGfvXmUiBHoH7EwJc',
    appId: '1:533485142059:ios:6c65799b1816956b252a6e',
    messagingSenderId: '533485142059',
    projectId: 'app-mais-saude-73627',
    storageBucket: 'app-mais-saude-73627.appspot.com',
    iosBundleId: 'com.example.appMaisSaude',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjvig4a9wl_TKUJJ7SocfR_pD9yLkL8vs',
    appId: '1:533485142059:web:c97f8ec479244d31252a6e',
    messagingSenderId: '533485142059',
    projectId: 'app-mais-saude-73627',
    authDomain: 'app-mais-saude-73627.firebaseapp.com',
    storageBucket: 'app-mais-saude-73627.appspot.com',
    measurementId: 'G-YYSG1CCZLX',
  );
}
